// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2667.Robot_2015Mecanum.commands;

import org.usfirst.frc2667.Robot_2015Mecanum.Robot;

import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class TurnAround extends Command {

	public double initialAngle;
	
    public TurnAround() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drivetrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	// The inital angle
    	initialAngle = Robot.drivetrain.getGyro().getAngle();
     	
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	Robot.drivetrain.mecanumDrive(0, 0, 0.6, Robot.drivetrain.getGyro().getAngle());
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return getAngleDiff() > 170;
    }
    
    public double getAngleDiff() {
    	return Math.abs((Robot.drivetrain.getGyro().getAngle() - initialAngle) % 360);
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.drivetrain.stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
}
