// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2667.Robot_2015Mecanum;
    
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.Gyro;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController drivetrainfrontRight;
    public static SpeedController drivetrainrearRight;
    public static SpeedController drivetrainrearLeft;
    public static SpeedController drivetrainfrontLeft;
    public static RobotDrive drivetrainRobotDrive41;
    public static Gyro drivetrainGyro;
    public static AnalogInput drivetrainAnalogInput1;
    public static SpeedController elevatorelevatorMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainfrontRight = new Talon(2);
        LiveWindow.addActuator("Drivetrain", "frontRight", (Talon) drivetrainfrontRight);
        
        drivetrainrearRight = new Talon(1);
        LiveWindow.addActuator("Drivetrain", "rearRight", (Talon) drivetrainrearRight);
        
        drivetrainrearLeft = new Talon(3);
        LiveWindow.addActuator("Drivetrain", "rearLeft", (Talon) drivetrainrearLeft);
        
        drivetrainfrontLeft = new Talon(4);
        LiveWindow.addActuator("Drivetrain", "frontLeft", (Talon) drivetrainfrontLeft);
        
        drivetrainRobotDrive41 = new RobotDrive(drivetrainfrontLeft, drivetrainrearLeft,
              drivetrainfrontRight, drivetrainrearRight);
        
        drivetrainRobotDrive41.setSafetyEnabled(false);
        drivetrainRobotDrive41.setExpiration(0.1);
        drivetrainRobotDrive41.setSensitivity(0.5);
        drivetrainRobotDrive41.setMaxOutput(0.5);
        drivetrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, true);
        drivetrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        drivetrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        drivetrainGyro = new Gyro(0);
        LiveWindow.addSensor("Drivetrain", "Gyro", drivetrainGyro);
        drivetrainGyro.setSensitivity(0.007);
        drivetrainAnalogInput1 = new AnalogInput(1);
        LiveWindow.addSensor("Drivetrain", "Analog Input 1", drivetrainAnalogInput1);
        
        elevatorelevatorMotor = new Talon(0);
        LiveWindow.addActuator("Elevator", "elevatorMotor", (Talon) elevatorelevatorMotor);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
